const MENU_DATA = [
  {
    id: 1,
    name: "Whooper",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "burgers",
  },
  {
    id: 2,
    name: "Whooper2",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "burgers",
  },
  {
    id: 3,
    name: "Whooper3",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "burgers",
  },
  {
    id: 4,
    name: "Whooper4",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "burgers",
  },
  {
    id: 5,
    name: "Whooper",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "burgers",
  },
  {
    id: 6,
    name: "Whooper2",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "burgers",
  },
  {
    id: 7,
    name: "Whooper3",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "burgers",
  },
  {
    id: 8,
    name: "Whooper4",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "burgers",
  },
  {
    id: 9,
    name: "Cola",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "drinks",
  },
  {
    id: 10,
    name: "Sprite",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "drinks",
  },
  {
    id: 11,
    name: "Orange Juice",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "drinks",
  },
  {
    id: 12,
    name: "Fries",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "Other",
  },
  {
    id: 13,
    name: "Onion rings",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "Other",
  },
  {
    id: 14,
    name: "Salad",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    // routeName: "burgers",
    category: "Other",
  },
];

export default MENU_DATA;
